import type { APIRoute } from "astro";
import { site } from "../data/site";

export const prerender = true;

/**
 * Static robots.txt — Allow public pages, point crawlers at the sitemap.
 * Accessible at /robots.txt
 */
export const GET: APIRoute = () => {
  const origin = site.url.replace(/\/$/, "");
  // Prefer standard index; also advertise /sitemap.xml alias (post-build)
  const body = `# ${site.name} / ${site.brand}
User-agent: *
Allow: /

# Primary sitemap index (generated by @astrojs/sitemap)
Sitemap: ${origin}/sitemap-index.xml
# Convenience alias (same content as index when present)
Sitemap: ${origin}/sitemap.xml
`;

  return new Response(body, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=3600",
    },
  });
};
